debug = false
dbpath = "./data/data.db"

# At most 5 registration attempts per minute per IP
[ip_rate_limiter.register]
enable = false
max_requests = 5
window_ms = 60000

# At most 10 login attempts per minute per IP
[ip_rate_limiter.login]
enable = false
max_requests = 15
window_ms = 10000

# At most 1 profile request/second per IP
[ip_rate_limiter.profile]
enable = false
max_requests = 1
window_ms = 1000

# At most 10 logout attempts per minute per IP
[ip_rate_limiter.logout]
enable = false
max_requests = 10
window_ms = 60000